# generated by cabal-rpm-2.3.3 --bundle
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Haskell/

%global lensfamilyth lens-family-th-0.5.3.2
%global linuxcapabilities linux-capabilities-0.1.1.0
%global thenv th-env-0.1.1
%global withutf8 with-utf8-1.1.0.0

%global subpkgs %{lensfamilyth} %{linuxcapabilities} %{thenv} %{withutf8}

Name:           podenv
Version:        0.9.0
Release:        1%{?dist}
Summary:        A container wrapper

License:        Apache-2.0
URL:            https://hackage.haskell.org/package/podenv
# Begin cabal-rpm sources:
Source0:        https://github.com/podenv/podenv/archive/refs/tags/v%{version}.tar.gz#/%{name}-%{version}.tar.gz
Source1:        https://hackage.haskell.org/package/%{lensfamilyth}/%{lensfamilyth}.tar.gz
Source2:        https://hackage.haskell.org/package/%{linuxcapabilities}/%{linuxcapabilities}.tar.gz
Source3:        https://hackage.haskell.org/package/%{thenv}/%{thenv}.tar.gz
Source4:        https://hackage.haskell.org/package/%{withutf8}/%{withutf8}.tar.gz
# End cabal-rpm sources

# Begin cabal-rpm deps:
BuildRequires:  ghc-rpm-macros-extra
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-SHA-devel
BuildRequires:  ghc-aeson-devel
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-dhall-devel
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-either-devel
BuildRequires:  ghc-filepath-devel
BuildRequires:  ghc-gitrev-devel
BuildRequires:  ghc-lens-family-core-devel
#BuildRequires:  ghc-lens-family-th-devel
#BuildRequires:  ghc-linux-capabilities-devel
BuildRequires:  ghc-optparse-applicative-devel
BuildRequires:  ghc-relude-devel
BuildRequires:  ghc-text-devel
#BuildRequires:  ghc-th-env-devel
BuildRequires:  ghc-time-devel
BuildRequires:  ghc-typed-process-devel
BuildRequires:  ghc-unix-devel
#BuildRequires:  ghc-with-utf8-devel
BuildRequires:  help2man
# for missing dep 'lens-family-th':
BuildRequires:  ghc-template-haskell-devel
# for missing dep 'th-env':
BuildRequires:  ghc-template-haskell-devel
BuildRequires:  ghc-th-compat-devel
# for missing dep 'with-utf8':
BuildRequires:  ghc-process-devel
BuildRequires:  ghc-safe-exceptions-devel
# End cabal-rpm deps
Requires:       podman

%description
Podenv provides a declarative interface to manage containerized applications.

Using rootless containers, podenv let you run applications seamlessly.


%prep
# Begin cabal-rpm setup:
%setup -q -a1 -a2 -a3 -a4
# End cabal-rpm setup

( cd %{withutf8}
  cabal-tweak-dep-ver base '<4.20' '<4.22'
  cabal-tweak-dep-ver filepath '<1.5' '<1.6'
)


%build
# Begin cabal-rpm build:
%ghc_libs_build -P -H %{subpkgs}
%ghc_bin_build
# End cabal-rpm build


%install
# Begin cabal-rpm install
%ghc_bin_install
rm -r %{buildroot}%{ghclibdir}

set noclobber
mkdir -p %{buildroot}%{bash_completions_dir}
mkdir -p %{buildroot}%{fish_completions_dir}
mkdir -p %{buildroot}%{zsh_completions_dir}
%{buildroot}%{_bindir}/%{name} --bash-completion-script %{name} | sed s/filenames/default/ > %{buildroot}%{bash_completions_dir}/%{name}
%{buildroot}%{_bindir}/%{name} --fish-completion-script %{name} > %{buildroot}%{fish_completions_dir}/%{name}
%{buildroot}%{_bindir}/%{name} --zsh-completion-script %{name} | sed s/filenames/default/ > %{buildroot}%{zsh_completions_dir}/_%{name}

mkdir -p %{buildroot}%{_mandir}/man1/
help2man --no-info %{buildroot}%{_bindir}/%{name} > %{buildroot}%{_mandir}/man1/%{name}.1
# End cabal-rpm install


%files
# Begin cabal-rpm files:
%license LICENSE
%doc CHANGELOG.md README.md
%{_bindir}/%{name}
%{bash_completions_dir}/%{name}
%{fish_completions_dir}/%{name}
%{zsh_completions_dir}/_%{name}
%{_mandir}/man1/%{name}.1*
# End cabal-rpm files


%changelog
* Mon Mar 30 2026 Jens Petersen <petersen@redhat.com> - 0.9.0-1
- https://github.com/podenv/podenv/blob/v0.9.0/CHANGELOG.md

* Fri Feb 21 2025 Jens Petersen  <petersen@redhat.com> - 0.7.0-1
- https://github.com/podenv/podenv/blob/v0.7.0/CHANGELOG.md

* Wed Aug 10 2022 Jens Petersen <petersen@redhat.com> - 0.2.0-1
- https://hackage.haskell.org/package/podenv-0.2.0/changelog

* Sat May 14 2022 Jens Petersen <petersen@redhat.com> - 0.1.0-1
- initial stable release

* Sat Jan  8 2022 Jens Petersen <petersen@redhat.com> - 0.1.0.0-0.20220107
- update to 222e906
- https://github.com/podenv/podenv/commits/main

* Fri Dec  3 2021 Jens Petersen <petersen@redhat.com> - 0.1.0.0-0.20211202
- update to 8f1cd6b

* Wed Nov  3 2021 Jens Petersen <petersen@redhat.com> - 0.1.0.0-0.20211103
- update to 53e4455

* Tue Nov  2 2021 Jens Petersen <petersen@redhat.com> - 0.1.0.0-0.20211101
- update to b7e4c7a

* Mon Nov  1 2021 Jens Petersen <petersen@redhat.com> - 0.1.0.0-0.20211030
- update to c9eea03

* Tue Oct 26 2021 Jens Petersen <petersen@redhat.com> - 0.1.0.0-0.20211026
- update to 692682a

* Mon Oct 25 2021 Jens Petersen <petersen@redhat.com> - 0.1.0.0-0.20211025
- update to 5b1e758

* Mon Oct 18 2021 Jens Petersen <petersen@redhat.com> - 0.1.0.0-0.20211018
- update to d0f8b27
- short githash for snapshot should now appear in --version

* Mon Oct  4 2021 Jens Petersen <petersen@redhat.com> - 0.1.0.0-0.20211004
- update to a9c241a

* Thu Sep 23 2021 Jens Petersen <petersen@redhat.com> - 0.1.0.0-0.20210923.1
- update to 87838f7 tarball

* Thu Sep 23 2021 Jens Petersen <petersen@redhat.com> - 0.1.0.0-0.20210923
- update to be20ef4

* Wed Sep 22 2021 Jens Petersen <petersen@redhat.com> - 0.1.0.0-0.20210922
- initial packaging
