# generated by cabal-rpm-2.1.0 --subpackage
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Haskell/

%undefine with_ghc_prof
%undefine with_haddock
%global without_prof 1
%global without_haddock 1
%global debug_package %{nil}

Name:           podenv
Version:        0.1.0.0
Release:        0.20210920gitbef8daa
Summary:        A podman wrapper

License:        ASL 2.0
Url:            https://github.com/podenv/podenv
Patch0:         podenv-dhall-lowerbound.patch

# Begin cabal-rpm deps:
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
BuildRequires:  ghc-SHA-devel
BuildRequires:  ghc-base-devel
BuildRequires:  ghc-containers-devel
BuildRequires:  ghc-dhall-devel
BuildRequires:  ghc-directory-devel
BuildRequires:  ghc-either-devel
BuildRequires:  ghc-filepath-devel
BuildRequires:  ghc-lens-family-core-devel
#BuildRequires:  ghc-lens-family-th-devel
#BuildRequires:  ghc-linux-capabilities-devel
BuildRequires:  ghc-optparse-applicative-devel
BuildRequires:  ghc-relude-devel
BuildRequires:  ghc-text-devel
BuildRequires:  ghc-typed-process-devel
BuildRequires:  ghc-unix-devel
BuildRequires:  cabal-install > 1.18
# for missing dep 'lens-family-th':
BuildRequires:  ghc-template-haskell-devel
# End cabal-rpm deps
BuildRequires:  git-core

%description
Podenv provides a declarative interface to manage containerized application.
Using rootless containers, podenv let's you run applications seamlessly.


%prep
if [ ! -d podenv ]; then
git clone https://github.com/podenv/podenv.git
%setup -q -D -T -n podenv
git submodule init
git submodule update
%patch0 -p1 -b .orig
fi


%build
# Begin cabal-rpm build:
cabal update
cabal build
# End cabal-rpm build


%install
mkdir -p %{buildroot}%{_bindir}
strip -s -o %{buildroot}%{_bindir}/podenv dist-newstyle/build/*/ghc-*/podenv-%{version}/x/podenv/build/podenv/podenv
# Begin cabal-rpm install
mkdir -p %{buildroot}%{_datadir}/bash-completion/completions/
%{buildroot}%{_bindir}/%{name} --bash-completion-script %{name} | sed s/filenames/default/ > %{buildroot}%{_datadir}/bash-completion/completions/%{name}
# End cabal-rpm install


%files
# Begin cabal-rpm files:
%license LICENSE
%doc README.md
%{_bindir}/%{name}
%{_datadir}/bash-completion/completions/%{name}
# End cabal-rpm files


%changelog
* Tue Sep 21 2021 Jens Petersen <petersen@redhat.com> - 0.1.0.0-1
- initial packaging
